/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButtonMenuItem;
import javax.swing.JSpinner;
import javax.swing.JTextField;

/**
 *
 * @author Yonathan
 */
public class FormDocenteModif extends javax.swing.JFrame {

    /**
     * Creates new form FormDocente
     */
    public FormDocenteModif() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jpnModifDocente = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtDui = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        spnFechaNacimiento = new javax.swing.JSpinner();
        cbGradoAcademico = new javax.swing.JComboBox<>();
        cbEspecialidad = new javax.swing.JComboBox<>();
        btnCancelarDocente = new javax.swing.JButton();
        btnGuardarDocente = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        cbTipoContrato = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("DUI:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nombre(s):");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Apellido(s):");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Correo electrónico:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Teléfono:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Fecha de Nacimiento:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Tipo de contrato:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Especialidad:");

        txtDui.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDui.setText("00000000-0");

        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNombre.setText("Nombres del docente");

        txtTelefono.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTelefono.setText("+503 0000-0000");

        txtApellido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtApellido.setText("Apellidos del docente");

        txtCorreo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCorreo.setText("usuario@dominio.com");

        spnFechaNacimiento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        spnFechaNacimiento.setModel(new javax.swing.SpinnerDateModel());
        spnFechaNacimiento.setEditor(new javax.swing.JSpinner.DateEditor(spnFechaNacimiento, "yyyy-MM-dd"));

        cbGradoAcademico.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbGradoAcademico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Técnico", "Profesorado",
                "Licenciatura", "Ingeniería", "Arquitectura", "Maestría", "Doctorado" }));

        cbEspecialidad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbEspecialidad.setModel(new javax.swing.DefaultComboBoxModel<>(
                new String[] { "Educación", "Artes y humanidades", "Ciencias sociales", "Ciencias económicas",
                        "Derecho", "Ciencias naturales", "Matemática y estadística", "TIC's", "Industria",
                        "Construcción", "Agricultura", "Salud y bienestar", "Servicios" }));
        cbEspecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEspecialidadActionPerformed(evt);
            }
        });

        btnCancelarDocente.setBackground(new java.awt.Color(204, 204, 204));
        btnCancelarDocente.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnCancelarDocente.setText("Cancelar");
        btnCancelarDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarDocenteActionPerformed(evt);
            }
        });

        btnGuardarDocente.setBackground(new java.awt.Color(204, 255, 204));
        btnGuardarDocente.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnGuardarDocente.setText("Guardar Docente");
        btnGuardarDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarDocenteActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Grado Académico:");

        cbTipoContrato.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbTipoContrato.setModel(
                new javax.swing.DefaultComboBoxModel<>(new String[] { "Permanente", "Temporal", "Por horas clase" }));

        jLabel10.setText("INGRESE LOS CAMPOS A MODIFICAR");

        javax.swing.GroupLayout jpnModifDocenteLayout = new javax.swing.GroupLayout(jpnModifDocente);
        jpnModifDocente.setLayout(jpnModifDocenteLayout);
        jpnModifDocenteLayout.setHorizontalGroup(
                jpnModifDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpnModifDocenteLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(jpnModifDocenteLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jpnModifDocenteLayout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jpnModifDocenteLayout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnModifDocenteLayout
                                                .createSequentialGroup()
                                                .addGroup(jpnModifDocenteLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(jpnModifDocenteLayout.createSequentialGroup()
                                                                .addComponent(btnCancelarDocente,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 111,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(btnGuardarDocente,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 150,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(txtCorreo,
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jpnModifDocenteLayout.createSequentialGroup()
                                                                .addGroup(jpnModifDocenteLayout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(txtTelefono,
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(txtDui,
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(cbEspecialidad,
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                0, 227, Short.MAX_VALUE)
                                                                        .addComponent(cbTipoContrato,
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                0, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                jpnModifDocenteLayout
                                                                                        .createSequentialGroup()
                                                                                        .addComponent(jLabel8)
                                                                                        .addGap(0, 0, Short.MAX_VALUE))
                                                                        .addGroup(jpnModifDocenteLayout
                                                                                .createSequentialGroup()
                                                                                .addGroup(jpnModifDocenteLayout
                                                                                        .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                        .addComponent(jLabel7)
                                                                                        .addComponent(jLabel1,
                                                                                                javax.swing.GroupLayout.Alignment.LEADING))
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                        Short.MAX_VALUE)))
                                                                .addGroup(jpnModifDocenteLayout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(jpnModifDocenteLayout
                                                                                .createSequentialGroup()
                                                                                .addGap(62, 62, 62)
                                                                                .addGroup(jpnModifDocenteLayout
                                                                                        .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addGroup(jpnModifDocenteLayout
                                                                                                .createSequentialGroup()
                                                                                                .addGroup(
                                                                                                        jpnModifDocenteLayout
                                                                                                                .createParallelGroup(
                                                                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(
                                                                                                                        jLabel3)
                                                                                                                .addComponent(
                                                                                                                        jLabel6)
                                                                                                                .addComponent(
                                                                                                                        jLabel9))
                                                                                                .addGap(0, 0,
                                                                                                        Short.MAX_VALUE))
                                                                                        .addComponent(
                                                                                                spnFechaNacimiento)
                                                                                        .addComponent(cbGradoAcademico,
                                                                                                0,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                        .addComponent(txtApellido,
                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)))
                                                                        .addGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                jpnModifDocenteLayout
                                                                                        .createSequentialGroup()
                                                                                        .addPreferredGap(
                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                58, Short.MAX_VALUE)
                                                                                        .addGroup(jpnModifDocenteLayout
                                                                                                .createParallelGroup(
                                                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                .addComponent(jLabel2)
                                                                                                .addComponent(txtNombre,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                        240,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                                .addGap(42, 42, 42))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                jpnModifDocenteLayout.createSequentialGroup()
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel10)
                                        .addGap(204, 204, 204)));
        jpnModifDocenteLayout.setVerticalGroup(
                jpnModifDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpnModifDocenteLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel10)
                                .addGap(27, 27, 27)
                                .addGroup(jpnModifDocenteLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jpnModifDocenteLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtDui, javax.swing.GroupLayout.PREFERRED_SIZE, 28,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 28,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jpnModifDocenteLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jpnModifDocenteLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtTelefono)
                                        .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 29,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25,
                                        Short.MAX_VALUE)
                                .addGroup(jpnModifDocenteLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jpnModifDocenteLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cbTipoContrato)
                                        .addComponent(spnFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22,
                                        Short.MAX_VALUE)
                                .addGroup(jpnModifDocenteLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jpnModifDocenteLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cbGradoAcademico, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 34,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addGroup(jpnModifDocenteLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnCancelarDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 31,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnGuardarDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 31,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jpnModifDocente, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(14, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(29, Short.MAX_VALUE)
                                .addComponent(jpnModifDocente, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap()));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbEspecialidadActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cbEspecialidadActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_cbEspecialidadActionPerformed

    private void btnGuardarDocenteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnGuardarDocenteActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnGuardarDocenteActionPerformed

    private void btnCancelarDocenteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCancelarDocenteActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnCancelarDocenteActionPerformed

    public JButton getBtnCancelarDocente() {
        return btnCancelarDocente;
    }

    public JButton getBtnGuardarDocente() {
        return btnGuardarDocente;
    }

    public JComboBox<String> getCbEspecialidad() {
        return cbEspecialidad;
    }

    public JComboBox<String> getCbGradoAcademico() {
        return cbGradoAcademico;
    }

    public JComboBox<String> getCbTipoContrato() {
        return cbTipoContrato;
    }

    public JRadioButtonMenuItem getjRadioButtonMenuItem1() {
        return jRadioButtonMenuItem1;
    }

    public JSpinner getSpnFechaNacimiento() {
        return spnFechaNacimiento;
    }

    public JTextField getTxtApellido() {
        return txtApellido;
    }

    public JTextField getTxtCorreo() {
        return txtCorreo;
    }

    public JTextField getTxtDui() {
        return txtDui;
    }

    public JTextField getTxtNombre() {
        return txtNombre;
    }

    public JTextField getTxtTelefono() {
        return txtTelefono;
    }

    // SETTER

    public void setBtnCancelarDocente(JButton btnCancelarDocente) {
        this.btnCancelarDocente = btnCancelarDocente;
    }

    public void setBtnGuardarDocente(JButton btnGuardarDocente) {
        this.btnGuardarDocente = btnGuardarDocente;
    }

    public void setCbEspecialidad(JComboBox<String> cbEspecialidad) {
        this.cbEspecialidad = cbEspecialidad;
    }

    public void setCbGradoAcademico(JComboBox<String> cbGradoAcademico) {
        this.cbGradoAcademico = cbGradoAcademico;
    }

    public void setCbTipoContrato(JComboBox<String> cbTipoContrato) {
        this.cbTipoContrato = cbTipoContrato;
    }

    public void setjRadioButtonMenuItem1(JRadioButtonMenuItem jRadioButtonMenuItem1) {
        this.jRadioButtonMenuItem1 = jRadioButtonMenuItem1;
    }

    public void setSpnFechaNacimiento(JSpinner spnFechaNacimiento) {
        this.spnFechaNacimiento = spnFechaNacimiento;
    }

    public void setTxtApellido(JTextField txtApellido) {
        this.txtApellido = txtApellido;
    }

    public void setTxtCorreo(JTextField txtCorreo) {
        this.txtCorreo = txtCorreo;
    }

    public void setTxtDui(JTextField txtDui) {
        this.txtDui = txtDui;
    }

    public void setTxtNombre(JTextField txtNombre) {
        this.txtNombre = txtNombre;
    }

    public void setTxtTelefono(JTextField txtTelefono) {
        this.txtTelefono = txtTelefono;
    }

    public JPanel getJpnModifDocente() {
        return jpnModifDocente;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarDocente;
    private javax.swing.JButton btnGuardarDocente;
    private javax.swing.JComboBox<String> cbEspecialidad;
    private javax.swing.JComboBox<String> cbGradoAcademico;
    private javax.swing.JComboBox<String> cbTipoContrato;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JPanel jpnModifDocente;
    private javax.swing.JSpinner spnFechaNacimiento;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDui;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
